### ISSUE TITLE
DeleteQueue/CreateQueue resuscitates the deleted queue

### ISSUE THREAD

**Issue by ierceg** [iain/fake_sqs#19]
I have Fake SQS running as a service in a docker container (see [spurious io](https://github.com/spurious-io)). My tests use a single queue name which thus gets to be deleted and recreated multiple times during the test run. The problem is that while on DeleteQueue, the queue disappears from the list of queues, on CreateQueue the old queue is created (which can be seen in the number of available/visible messages which remains the same before the delete and after the create).

Is this by design? Is there anything I can do about it short of creating a PR?

**Comment by tiwilliam** [comment]
I can't replicate this issue, created a test case for it as well:
https://github.com/iain/fake_sqs/commit/b3e979409f5a737b0ed200d548fe472c121abf41
