### ISSUE TITLE
v0.3.0 - Still throwing QueueNameExists error if queue exists

### ISSUE THREAD

**Issue by ericwubgl** [iain/fake_sqs#26]
Error create queue name devtest_DynamoDBFailed: devtest_DynamoDBFailed (Service: AmazonSQS; Status Code: 400; Error Code: QueueNameExists; Request ID: cfc454d8-47d4-4c08-a6fa-c3a5b0f096d6)

Trace from fake_sqs console:
2015-10-05 14:38:07 - FakeSQS::QueueNameExists - devtest_DynamoDBFailed:
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.0/lib/fake_sqs/queues.rb:18:in `create'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.0/lib/fake_sqs/actions/create_queue.rb:13:in`call'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.0/lib/fake_sqs/api.rb:39:in `block in call'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.0/lib/fake_sqs/queues.rb:51:in`block in transaction'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.0/lib/fake_sqs/memory_database.rb:24:in `transaction'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.0/lib/fake_sqs/queues.rb:50:in`transaction'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.0/lib/fake_sqs/api.rb:38:in `call'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.0/lib/fake_sqs/web_interface.rb:39:in`block in class:WebInterface'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in`block in compile!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in`block (3 levels) in route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in`block (2 levels) in route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in`catch'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in`block in route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in`route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`block in invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in`block in call!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`catch'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in`call!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.0/lib/fake_sqs/catch_errors.rb:12:in`call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in`call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in`call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in`call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/nulllogger.rb:9:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/head.rb:13:in`call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in`call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`block in call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in `service'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in`service'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in`block in start_thread'
localhost - - [05/Oct/2015:14:38:07 AEDT] "POST / HTTP/1.1" 400 211

**Comment by tiwilliam** [comment]
Not an issue in latest version.
