### ISSUE TITLE
Simple way to create a queue programmatically

### ISSUE THREAD

**Issue by julik** [iain/fake_sqs#41]
Our applications are set up with a single `SQS_QUEUE_URL`, which we then feed to the various AWS SDK parts. This incorporates the queue name by default. What would be the simplest way to create the queue with a name programmatically, before I call

```
app = FakeSQS.to_rack(options)
app.set :server, 'webrick' # app is a Sinatra::Base application
app.queues.create(name) # <--- how to do this?
app.run!
```

I would like to do this bypassing the AWS SDK, for simplicity's sake. I could of course create a new thread in the same process and use the AWS SDK to create the queue via the "official" way but it seems a bit of an overkill. Ideally I would like to pass the value parsed from the URL before I even start the service.

**Comment by tiwilliam** [comment]
I guess this has already been solved, if not, open again.
