### ISSUE TITLE
Support endpoint aliases

### ISSUE THREAD

**Issue by umcodemonkey** [iain/fake_sqs#43]
If fake_sqs is running behind a proxy, the "host" portion of the queues returned always reference the host to which the server is bound, rather than the host on the request. It would be helpful for proxies if fake_sqs would use the hostname in the HTTP request when describing queues. This is especially useful in docker-compose based dev workflows where fake_sqs is being accessed through a docker network name.

**Comment by aarongreenlee** [comment]
I may be having the same troubles here. We're trying to setup fake_sqs using Docker Compose and our GO application but the returned addresses of our created queues are `0.0.0.0.`.

@umcodemonkey, are you able to connect from your app?

Thanks,

Aaron

**Comment by umcodemonkey** [comment]
No, we never solved this issue and went back to using personal development queues in live SQS.

**Comment by umcodemonkey** [comment]
@aarongreenlee I implemented a fix for this in PR #44.

**Comment by aarongreenlee** [comment]
Thanks for the reply, @umcodemonkey. We opted to create queues on demand and terminate them when our CI build is over.

**Comment by tiwilliam** [comment]
Fixed in #44.
