### ISSUE TITLE
Allow configurable startup timeout

### ISSUE THREAD

**Issue by duncan-bayne** [iain/fake_sqs#46]
Currently, the timeout is configurable `wait_until_up`:

```
    def wait_until_up(deadline = Time.now + 2)
```

... but that parameter is used nowhere else in the code.  Perhaps this should be taken from `@options` passed into the constructor?

**Comment by tiwilliam** [comment]
Fixed in 94a1e38593f2b5eb590dadc337a4a1579314b912.
